### ISSUE TITLE
Code generation not working

### ISSUE THREAD

**Issue by rikousik** [ShiroYacha/flutter_design#1]
**When I'm trying to build code it gives me this warning and errors then fails the build.** 

[WARNING] ../../../Dev/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_design_codegen-0.0.11-pre+1/lib/src/ast.dart:24:7: Error: The non-abstract class 'ToSourceIgnoringDesignAnnotationsVisitor' is missing implementations for these members:
 - AstVisitor.visitConstructorSelector
 - AstVisitor.visitEnumConstantArguments
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class ToSourceIgnoringDesignAnnotationsVisitor implements AstVisitor<void> {
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../../Dev/flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-3.3.1/lib/dart/ast/ast.dart:405:6: Context: 'AstVisitor.visitConstructorSelector' is defined here.
  R? visitConstructorSelector(ConstructorSelector node);
     ^^^^^^^^^^^^^^^^^^^^^^^^
../../../Dev/flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-3.3.1/lib/dart/ast/ast.dart:423:6: Context: 'AstVisitor.visitEnumConstantArguments' is defined here.
  R? visitEnumConstantArguments(EnumConstantArguments node);
     ^^^^^^^^^^^^^^^^^^^^^^^^^^
[INFO] Precompiling build script... completed, took 949ms

[SEVERE] Failed to precompile build script .dart_tool/build/entrypoint/build.dart.
This is likely caused by a misconfigured builder definition.

**Comment by ShiroYacha** [comment]
Hi, sorry i forgot to update the readme file. You might need to add this `dependency_overrides` to the `pubspec.yaml` file:

```
dependency_overrides:
  analyzer: 3.2.0
```

Could you try and retest it? I am trying to find a solution that doesn't require this fix on different flutter versions.

Thanks!

**Comment by rikousik** [comment]
Only overriding analyzer didn't help, found out that I have to override dart style also. 
So, this helped me finally: 

dependency_overrides:
  analyzer: 3.2.0 
  dart_style: 2.2.1

**Comment by ShiroYacha** [comment]
Thanks for the info, i'll update the readme accordingly :)
